// SPDX-License-Identifier: MIT
#pragma once

// Namespace all externally visible RYDE-1F symbols to avoid clashes with
// other OQS algorithms (including additional RYDE parameter sets).
//
// This header is force-included via the build system for every source file that
// belongs to the RYDE-1F reference implementation and its glue layer. It ensures
// that both declarations and definitions are rewritten to the corresponding
// OQS-prefixed symbols, eliminating duplicate symbol definitions when multiple
// variants are linked together.

#define AES256_CTR_DRBG_struct OQS_RYDE1F_AES256_CTR_DRBG_struct
#define AES256_CTR_DRBG_Update OQS_RYDE1F_AES256_CTR_DRBG_Update
#define AES256_ECB OQS_RYDE1F_AES256_ECB
#define crypto_sign OQS_RYDE1F_crypto_sign
#define crypto_sign_keypair OQS_RYDE1F_crypto_sign_keypair
#define crypto_sign_open OQS_RYDE1F_crypto_sign_open
#define DRBG_ctx OQS_RYDE1F_DRBG_ctx
#define handleErrors OQS_RYDE1F_handleErrors
#define randombytes OQS_RYDE1F_randombytes
#define randombytes_init OQS_RYDE1F_randombytes_init
#define hash_sha3_init OQS_RYDE1F_hash_sha3_init
#define hash_sha3_absorb OQS_RYDE1F_hash_sha3_absorb
#define hash_sha3_finalize OQS_RYDE1F_hash_sha3_finalize
#define seedexpander_shake_init OQS_RYDE1F_seedexpander_shake_init
#define seedexpander_shake_get_bytes OQS_RYDE1F_seedexpander_shake_get_bytes
#define hash_sha3_x4_init OQS_RYDE1F_hash_sha3_x4_init
#define hash_sha3_x4_absorb OQS_RYDE1F_hash_sha3_x4_absorb
#define hash_sha3_x4_finalize OQS_RYDE1F_hash_sha3_x4_finalize
#define seedexpander_shake_x4_init OQS_RYDE1F_seedexpander_shake_x4_init
#define seedexpander_shake_x4_get_bytes OQS_RYDE1F_seedexpander_shake_x4_get_bytes

#define binary_matrix_add OQS_RYDE1F_binary_matrix_add
#define binary_matrix_copy OQS_RYDE1F_binary_matrix_copy
#define binary_matrix_from_string OQS_RYDE1F_binary_matrix_from_string
#define binary_matrix_mul_by_constant OQS_RYDE1F_binary_matrix_mul_by_constant
#define binary_matrix_mul_by_vector_left OQS_RYDE1F_binary_matrix_mul_by_vector_left
#define binary_matrix_mul_by_vector_right OQS_RYDE1F_binary_matrix_mul_by_vector_right
#define binary_matrix_print OQS_RYDE1F_binary_matrix_print
#define binary_matrix_random OQS_RYDE1F_binary_matrix_random
#define binary_matrix_set_to_zero OQS_RYDE1F_binary_matrix_set_to_zero
#define binary_matrix_to_string OQS_RYDE1F_binary_matrix_to_string
#define field_add OQS_RYDE1F_field_add
#define field_cmov OQS_RYDE1F_field_cmov
#define field_copy OQS_RYDE1F_field_copy
#define field_get_coefficient OQS_RYDE1F_field_get_coefficient
#define field_get_degree OQS_RYDE1F_field_get_degree
#define field_is_equal OQS_RYDE1F_field_is_equal
#define field_is_zero OQS_RYDE1F_field_is_zero
#define field_matrix_add OQS_RYDE1F_field_matrix_add
#define field_matrix_copy OQS_RYDE1F_field_matrix_copy
#define field_matrix_from_string OQS_RYDE1F_field_matrix_from_string
#define field_matrix_mul_by_vector_left OQS_RYDE1F_field_matrix_mul_by_vector_left
#define field_matrix_mul_by_vector_left_transpose OQS_RYDE1F_field_matrix_mul_by_vector_left_transpose
#define field_matrix_mul_by_vector_right OQS_RYDE1F_field_matrix_mul_by_vector_right
#define field_matrix_print OQS_RYDE1F_field_matrix_print
#define field_matrix_random OQS_RYDE1F_field_matrix_random
#define field_matrix_set_to_zero OQS_RYDE1F_field_matrix_set_to_zero
#define field_matrix_to_string OQS_RYDE1F_field_matrix_to_string
#define field_mul OQS_RYDE1F_field_mul
#define field_print OQS_RYDE1F_field_print
#define field_set_coefficient OQS_RYDE1F_field_set_coefficient
#define field_set_to_one OQS_RYDE1F_field_set_to_one
#define field_set_to_zero OQS_RYDE1F_field_set_to_zero
#define field_sqr OQS_RYDE1F_field_sqr
#define field_to_string OQS_RYDE1F_field_to_string
#define field_vector_add OQS_RYDE1F_field_vector_add
#define field_vector_copy OQS_RYDE1F_field_vector_copy
#define field_vector_from_string OQS_RYDE1F_field_vector_from_string
#define field_vector_gauss OQS_RYDE1F_field_vector_gauss
#define field_vector_get_rank OQS_RYDE1F_field_vector_get_rank
#define field_vector_mul_by_constant OQS_RYDE1F_field_vector_mul_by_constant
#define field_vector_print OQS_RYDE1F_field_vector_print
#define field_vector_random OQS_RYDE1F_field_vector_random
#define field_vector_random_full_rank_with_one OQS_RYDE1F_field_vector_random_full_rank_with_one
#define field_vector_set_to_zero OQS_RYDE1F_field_vector_set_to_zero
#define field_vector_to_string OQS_RYDE1F_field_vector_to_string

#define ryde_ggm_tree_expand OQS_RYDE1F_ryde_ggm_tree_expand
#define ryde_ggm_tree_get_leaves OQS_RYDE1F_ryde_ggm_tree_get_leaves
#define ryde_ggm_tree_get_sibling_path OQS_RYDE1F_ryde_ggm_tree_get_sibling_path
#define ryde_ggm_tree_partial_expand OQS_RYDE1F_ryde_ggm_tree_partial_expand
#define ryde_ggm_tree_print_sibling_path OQS_RYDE1F_ryde_ggm_tree_print_sibling_path
#define ryde_keygen OQS_RYDE1F_ryde_keygen
#define ryde_pack_matrices_and_vectors OQS_RYDE1F_ryde_pack_matrices_and_vectors
#define ryde_public_key_from_string OQS_RYDE1F_ryde_public_key_from_string
#define ryde_public_key_to_string OQS_RYDE1F_ryde_public_key_to_string
#define ryde_secret_key_from_string OQS_RYDE1F_ryde_secret_key_from_string
#define ryde_secret_key_to_string OQS_RYDE1F_ryde_secret_key_to_string
#define ryde_sign OQS_RYDE1F_ryde_sign
#define ryde_tcith_commit OQS_RYDE1F_ryde_tcith_commit
#define ryde_tcith_compute_polynomial_proof OQS_RYDE1F_ryde_tcith_compute_polynomial_proof
#define ryde_tcith_discard_input_challenge_2 OQS_RYDE1F_ryde_tcith_discard_input_challenge_2
#define ryde_tcith_expand_challenge_1 OQS_RYDE1F_ryde_tcith_expand_challenge_1
#define ryde_tcith_expand_challenge_2 OQS_RYDE1F_ryde_tcith_expand_challenge_2
#define ryde_tcith_expand_share OQS_RYDE1F_ryde_tcith_expand_share
#define ryde_tcith_phi OQS_RYDE1F_ryde_tcith_phi
#define ryde_tcith_psi OQS_RYDE1F_ryde_tcith_psi
#define ryde_tcith_recompute_polynomial_proof OQS_RYDE1F_ryde_tcith_recompute_polynomial_proof
#define ryde_unpack_matrices_and_vectors OQS_RYDE1F_ryde_unpack_matrices_and_vectors
#define ryde_verify OQS_RYDE1F_ryde_verify

#define KeccakP1600_Initialize OQS_RYDE1F_KeccakP1600_Initialize
#include <stdint.h>

void OQS_RYDE1F_KeccakP1600times4_StaticInitialize(void);
void OQS_RYDE1F_KeccakP1600times4_AddByte(void *states, unsigned int instanceIndex, unsigned char byte, unsigned int offset);

static inline void OQS_RYDE1F_KeccakP1600_AddByte(void *state, unsigned char byte, unsigned int offset) {
	uint64_t lane = (uint64_t)byte << ((offset % 8U) * 8U);
	((uint64_t *)state)[offset / 8U] ^= lane;
}

#define KeccakP1600_AddByte OQS_RYDE1F_KeccakP1600_AddByte
#define KeccakP1600_AddBytes OQS_RYDE1F_KeccakP1600_AddBytes
#define KeccakP1600_OverwriteBytes OQS_RYDE1F_KeccakP1600_OverwriteBytes
#define KeccakP1600_OverwriteWithZeroes OQS_RYDE1F_KeccakP1600_OverwriteWithZeroes
#define KeccakP1600_Permute_Nrounds OQS_RYDE1F_KeccakP1600_Permute_Nrounds
#define KeccakP1600_Permute_12rounds OQS_RYDE1F_KeccakP1600_Permute_12rounds
#define KeccakP1600_Permute_24rounds OQS_RYDE1F_KeccakP1600_Permute_24rounds
#define KeccakP1600_ExtractBytes OQS_RYDE1F_KeccakP1600_ExtractBytes
#define KeccakP1600_ExtractAndAddBytes OQS_RYDE1F_KeccakP1600_ExtractAndAddBytes
#define KeccakP1600_AddBytesInLane OQS_RYDE1F_KeccakP1600_AddBytesInLane
#define KeccakP1600_AddLanes OQS_RYDE1F_KeccakP1600_AddLanes
#define KeccakP1600_OverwriteBytesInLane OQS_RYDE1F_KeccakP1600_OverwriteBytesInLane
#define KeccakP1600_OverwriteLanes OQS_RYDE1F_KeccakP1600_OverwriteLanes
#define KeccakP1600_ExtractBytesInLane OQS_RYDE1F_KeccakP1600_ExtractBytesInLane
#define KeccakP1600_ExtractLanes OQS_RYDE1F_KeccakP1600_ExtractLanes
#define KeccakP1600_ExtractAndAddBytesInLane OQS_RYDE1F_KeccakP1600_ExtractAndAddBytesInLane
#define KeccakP1600_ExtractAndAddLanes OQS_RYDE1F_KeccakP1600_ExtractAndAddLanes
#define Keccak_HashInitialize OQS_RYDE1F_Keccak_HashInitialize
#define Keccak_HashInitializetimes4 OQS_RYDE1F_Keccak_HashInitializetimes4
#define Keccak_HashUpdate OQS_RYDE1F_Keccak_HashUpdate
#define Keccak_HashUpdatetimes4 OQS_RYDE1F_Keccak_HashUpdatetimes4
#define Keccak_HashFinal OQS_RYDE1F_Keccak_HashFinal
#define Keccak_HashFinaltimes4 OQS_RYDE1F_Keccak_HashFinaltimes4
#define Keccak_HashSqueeze OQS_RYDE1F_Keccak_HashSqueeze
#define Keccak_HashSqueezetimes4 OQS_RYDE1F_Keccak_HashSqueezetimes4
#define KeccakSponge OQS_RYDE1F_KeccakSponge
#define KeccakSpongeInitialize OQS_RYDE1F_KeccakSpongeInitialize
#define KeccakSpongeAbsorb OQS_RYDE1F_KeccakSpongeAbsorb
#define KeccakSpongeAbsorbLastFewBits OQS_RYDE1F_KeccakSpongeAbsorbLastFewBits
#define KeccakSpongeSqueeze OQS_RYDE1F_KeccakSpongeSqueeze
#define KeccakWidth1600_Sponge OQS_RYDE1F_KeccakWidth1600_Sponge
#define KeccakWidth1600_SpongeAbsorb OQS_RYDE1F_KeccakWidth1600_SpongeAbsorb
#define KeccakWidth1600_SpongeAbsorbLastFewBits OQS_RYDE1F_KeccakWidth1600_SpongeAbsorbLastFewBits
#define KeccakWidth1600_SpongeInitialize OQS_RYDE1F_KeccakWidth1600_SpongeInitialize
#define KeccakWidth1600_SpongeSqueeze OQS_RYDE1F_KeccakWidth1600_SpongeSqueeze
#define KeccakWidth1600_12rounds_Sponge OQS_RYDE1F_KeccakWidth1600_12rounds_Sponge
#define KeccakWidth1600_12rounds_SpongeInitialize OQS_RYDE1F_KeccakWidth1600_12rounds_SpongeInitialize
#define KeccakWidth1600_12rounds_SpongeAbsorb OQS_RYDE1F_KeccakWidth1600_12rounds_SpongeAbsorb
#define KeccakWidth1600_12rounds_SpongeAbsorbLastFewBits OQS_RYDE1F_KeccakWidth1600_12rounds_SpongeAbsorbLastFewBits
#define KeccakWidth1600_12rounds_SpongeSqueeze OQS_RYDE1F_KeccakWidth1600_12rounds_SpongeSqueeze
#define KeccakWidth1600times4_SpongeAbsorb OQS_RYDE1F_KeccakWidth1600times4_SpongeAbsorb
#define KeccakWidth1600times4_SpongeAbsorbLastFewBits OQS_RYDE1F_KeccakWidth1600times4_SpongeAbsorbLastFewBits
#define KeccakWidth1600times4_SpongeInitialize OQS_RYDE1F_KeccakWidth1600times4_SpongeInitialize
#define KeccakWidth1600times4_SpongeSqueeze OQS_RYDE1F_KeccakWidth1600times4_SpongeSqueeze
#define KeccakP1600times4_AddByte OQS_RYDE1F_KeccakP1600times4_AddByte
#define KeccakP1600times4_AddBytes OQS_RYDE1F_KeccakP1600times4_AddBytes
#define KeccakP1600times4_AddLanesAll OQS_RYDE1F_KeccakP1600times4_AddLanesAll
#define KeccakP1600times4_ExtractAndAddBytes OQS_RYDE1F_KeccakP1600times4_ExtractAndAddBytes
#define KeccakP1600times4_ExtractAndAddLanesAll OQS_RYDE1F_KeccakP1600times4_ExtractAndAddLanesAll
#define KeccakP1600times4_ExtractBytes OQS_RYDE1F_KeccakP1600times4_ExtractBytes
#define KeccakP1600times4_ExtractLanesAll OQS_RYDE1F_KeccakP1600times4_ExtractLanesAll
#define KeccakP1600times4_InitializeAll OQS_RYDE1F_KeccakP1600times4_InitializeAll
#define KeccakP1600times4_OverwriteBytes OQS_RYDE1F_KeccakP1600times4_OverwriteBytes
#define KeccakP1600times4_OverwriteLanesAll OQS_RYDE1F_KeccakP1600times4_OverwriteLanesAll
#define KeccakP1600times4_OverwriteWithZeroes OQS_RYDE1F_KeccakP1600times4_OverwriteWithZeroes
#define KeccakP1600times4_PermuteAll_12rounds OQS_RYDE1F_KeccakP1600times4_PermuteAll_12rounds
#define KeccakP1600times4_PermuteAll_24rounds OQS_RYDE1F_KeccakP1600times4_PermuteAll_24rounds
#define KeccakP1600times4_PermuteAll_4rounds OQS_RYDE1F_KeccakP1600times4_PermuteAll_4rounds
#define KeccakP1600times4_PermuteAll_6rounds OQS_RYDE1F_KeccakP1600times4_PermuteAll_6rounds
#define KeccakP1600times4_StaticInitialize OQS_RYDE1F_KeccakP1600times4_StaticInitialize
#define KeccakF1600_FastLoop_Absorb OQS_RYDE1F_KeccakF1600_FastLoop_Absorb
#define KeccakP1600_12rounds_FastLoop_Absorb OQS_RYDE1F_KeccakP1600_12rounds_FastLoop_Absorb
#define KECCAK_IMPL_NAMESPACE OQS_RYDE1F_KECCAK_IMPL_NAMESPACE

#define SHAKE128 OQS_RYDE1F_SHAKE128
#define SHAKE256 OQS_RYDE1F_SHAKE256
#define SHA3_224 OQS_RYDE1F_SHA3_224
#define SHA3_256 OQS_RYDE1F_SHA3_256
#define SHA3_384 OQS_RYDE1F_SHA3_384
#define SHA3_512 OQS_RYDE1F_SHA3_512
