// SPDX-License-Identifier: MIT
#pragma once

// Namespace all externally visible RYDE-1F symbols to avoid clashes with
// other OQS algorithms (including additional RYDE parameter sets).
//
// This header is force-included via the build system for every source file that
// belongs to the RYDE-1F reference implementation and its glue layer. It ensures
// that both declarations and definitions are rewritten to the corresponding
// OQS-prefixed symbols, eliminating duplicate symbol definitions when multiple
// variants are linked together.

#define AES256_CTR_DRBG_struct OQS_RYDE1F_AES256_CTR_DRBG_struct
#define AES256_CTR_DRBG_Update OQS_RYDE1F_AES256_CTR_DRBG_Update
#define AES256_ECB OQS_RYDE1F_AES256_ECB
#define crypto_sign OQS_RYDE1F_crypto_sign
#define crypto_sign_keypair OQS_RYDE1F_crypto_sign_keypair
#define crypto_sign_open OQS_RYDE1F_crypto_sign_open
#define DRBG_ctx OQS_RYDE1F_DRBG_ctx
#define handleErrors OQS_RYDE1F_handleErrors
#define randombytes OQS_RYDE1F_randombytes
#define randombytes_init OQS_RYDE1F_randombytes_init
#define hash_sha3_init OQS_RYDE1F_hash_sha3_init
#define hash_sha3_absorb OQS_RYDE1F_hash_sha3_absorb
#define hash_sha3_finalize OQS_RYDE1F_hash_sha3_finalize
#define seedexpander_shake_init OQS_RYDE1F_seedexpander_shake_init
#define seedexpander_shake_get_bytes OQS_RYDE1F_seedexpander_shake_get_bytes
#define hash_sha3_x4_init OQS_RYDE1F_hash_sha3_x4_init
#define hash_sha3_x4_absorb OQS_RYDE1F_hash_sha3_x4_absorb
#define hash_sha3_x4_finalize OQS_RYDE1F_hash_sha3_x4_finalize
#define seedexpander_shake_x4_init OQS_RYDE1F_seedexpander_shake_x4_init
#define seedexpander_shake_x4_get_bytes OQS_RYDE1F_seedexpander_shake_x4_get_bytes

#define KeccakP1600_Initialize OQS_RYDE1F_KeccakP1600_Initialize
#include <stdint.h>

static inline void OQS_RYDE1F_KeccakP1600_AddByte(void *state, unsigned char byte, unsigned int offset) {
	uint64_t lane = (uint64_t)byte << ((offset % 8U) * 8U);
	((uint64_t *)state)[offset / 8U] ^= lane;
}

#define KeccakP1600_AddByte OQS_RYDE1F_KeccakP1600_AddByte
#define KeccakP1600_AddBytes OQS_RYDE1F_KeccakP1600_AddBytes
#define KeccakP1600_OverwriteBytes OQS_RYDE1F_KeccakP1600_OverwriteBytes
#define KeccakP1600_OverwriteWithZeroes OQS_RYDE1F_KeccakP1600_OverwriteWithZeroes
#define KeccakP1600_Permute_Nrounds OQS_RYDE1F_KeccakP1600_Permute_Nrounds
#define KeccakP1600_Permute_12rounds OQS_RYDE1F_KeccakP1600_Permute_12rounds
#define KeccakP1600_Permute_24rounds OQS_RYDE1F_KeccakP1600_Permute_24rounds
#define KeccakP1600_ExtractBytes OQS_RYDE1F_KeccakP1600_ExtractBytes
#define KeccakP1600_ExtractAndAddBytes OQS_RYDE1F_KeccakP1600_ExtractAndAddBytes
#define KeccakP1600_AddBytesInLane OQS_RYDE1F_KeccakP1600_AddBytesInLane
#define KeccakP1600_AddLanes OQS_RYDE1F_KeccakP1600_AddLanes
#define KeccakP1600_OverwriteBytesInLane OQS_RYDE1F_KeccakP1600_OverwriteBytesInLane
#define KeccakP1600_OverwriteLanes OQS_RYDE1F_KeccakP1600_OverwriteLanes
#define KeccakP1600_ExtractBytesInLane OQS_RYDE1F_KeccakP1600_ExtractBytesInLane
#define KeccakP1600_ExtractLanes OQS_RYDE1F_KeccakP1600_ExtractLanes
#define KeccakP1600_ExtractAndAddBytesInLane OQS_RYDE1F_KeccakP1600_ExtractAndAddBytesInLane
#define KeccakP1600_ExtractAndAddLanes OQS_RYDE1F_KeccakP1600_ExtractAndAddLanes
#define Keccak_HashInitialize OQS_RYDE1F_Keccak_HashInitialize
#define Keccak_HashInitializetimes4 OQS_RYDE1F_Keccak_HashInitializetimes4
#define Keccak_HashUpdate OQS_RYDE1F_Keccak_HashUpdate
#define Keccak_HashUpdatetimes4 OQS_RYDE1F_Keccak_HashUpdatetimes4
#define Keccak_HashFinal OQS_RYDE1F_Keccak_HashFinal
#define Keccak_HashFinaltimes4 OQS_RYDE1F_Keccak_HashFinaltimes4
#define Keccak_HashSqueeze OQS_RYDE1F_Keccak_HashSqueeze
#define Keccak_HashSqueezetimes4 OQS_RYDE1F_Keccak_HashSqueezetimes4
#define KeccakSponge OQS_RYDE1F_KeccakSponge
#define KeccakSpongeInitialize OQS_RYDE1F_KeccakSpongeInitialize
#define KeccakSpongeAbsorb OQS_RYDE1F_KeccakSpongeAbsorb
#define KeccakSpongeAbsorbLastFewBits OQS_RYDE1F_KeccakSpongeAbsorbLastFewBits
#define KeccakSpongeSqueeze OQS_RYDE1F_KeccakSpongeSqueeze
#define KeccakWidth1600_Sponge OQS_RYDE1F_KeccakWidth1600_Sponge
#define KeccakWidth1600_SpongeAbsorb OQS_RYDE1F_KeccakWidth1600_SpongeAbsorb
#define KeccakWidth1600_SpongeAbsorbLastFewBits OQS_RYDE1F_KeccakWidth1600_SpongeAbsorbLastFewBits
#define KeccakWidth1600_SpongeInitialize OQS_RYDE1F_KeccakWidth1600_SpongeInitialize
#define KeccakWidth1600_SpongeSqueeze OQS_RYDE1F_KeccakWidth1600_SpongeSqueeze
#define KeccakWidth1600times4_SpongeAbsorb OQS_RYDE1F_KeccakWidth1600times4_SpongeAbsorb
#define KeccakWidth1600times4_SpongeAbsorbLastFewBits OQS_RYDE1F_KeccakWidth1600times4_SpongeAbsorbLastFewBits
#define KeccakWidth1600times4_SpongeInitialize OQS_RYDE1F_KeccakWidth1600times4_SpongeInitialize
#define KeccakWidth1600times4_SpongeSqueeze OQS_RYDE1F_KeccakWidth1600times4_SpongeSqueeze
#define KeccakP1600times4_AddByte OQS_RYDE1F_KeccakP1600times4_AddByte
#define KeccakP1600times4_AddBytes OQS_RYDE1F_KeccakP1600times4_AddBytes
#define KeccakP1600times4_AddLanesAll OQS_RYDE1F_KeccakP1600times4_AddLanesAll
#define KeccakP1600times4_ExtractAndAddBytes OQS_RYDE1F_KeccakP1600times4_ExtractAndAddBytes
#define KeccakP1600times4_ExtractAndAddLanesAll OQS_RYDE1F_KeccakP1600times4_ExtractAndAddLanesAll
#define KeccakP1600times4_ExtractBytes OQS_RYDE1F_KeccakP1600times4_ExtractBytes
#define KeccakP1600times4_ExtractLanesAll OQS_RYDE1F_KeccakP1600times4_ExtractLanesAll
#define KeccakP1600times4_InitializeAll OQS_RYDE1F_KeccakP1600times4_InitializeAll
#define KeccakP1600times4_OverwriteBytes OQS_RYDE1F_KeccakP1600times4_OverwriteBytes
#define KeccakP1600times4_OverwriteLanesAll OQS_RYDE1F_KeccakP1600times4_OverwriteLanesAll
#define KeccakP1600times4_OverwriteWithZeroes OQS_RYDE1F_KeccakP1600times4_OverwriteWithZeroes
#define KeccakP1600times4_PermuteAll_12rounds OQS_RYDE1F_KeccakP1600times4_PermuteAll_12rounds
#define KeccakP1600times4_PermuteAll_24rounds OQS_RYDE1F_KeccakP1600times4_PermuteAll_24rounds
#define KeccakP1600times4_PermuteAll_4rounds OQS_RYDE1F_KeccakP1600times4_PermuteAll_4rounds
#define KeccakP1600times4_PermuteAll_6rounds OQS_RYDE1F_KeccakP1600times4_PermuteAll_6rounds
#define KeccakP1600times4_StaticInitialize OQS_RYDE1F_KeccakP1600times4_StaticInitialize
#define KeccakF1600_FastLoop_Absorb OQS_RYDE1F_KeccakF1600_FastLoop_Absorb
#define KeccakP1600_12rounds_FastLoop_Absorb OQS_RYDE1F_KeccakP1600_12rounds_FastLoop_Absorb
#define KECCAK_IMPL_NAMESPACE OQS_RYDE1F_KECCAK_IMPL_NAMESPACE

#define SHAKE128 OQS_RYDE1F_SHAKE128
#define SHAKE256 OQS_RYDE1F_SHAKE256
#define SHA3_224 OQS_RYDE1F_SHA3_224
#define SHA3_256 OQS_RYDE1F_SHA3_256
#define SHA3_384 OQS_RYDE1F_SHA3_384
#define SHA3_512 OQS_RYDE1F_SHA3_512
