set(_LESS_OBJS "")

if(OQS_ENABLE_SIG_less_LESS_252_192)
    add_library(less_LESS_252_192_opt OBJECT sig_less_LESS_252_192.c less_LESS_252_192_opt/oqs_less.c less_LESS_252_192_opt/LESS.c less_LESS_252_192_opt/canonical.c less_LESS_252_192_opt/codes.c less_LESS_252_192_opt/fips202.c less_LESS_252_192_opt/keccakf1600.c less_LESS_252_192_opt/monomial.c less_LESS_252_192_opt/rng.c less_LESS_252_192_opt/seedtree.c less_LESS_252_192_opt/sort.c less_LESS_252_192_opt/transpose.c less_LESS_252_192_opt/utils.c)
    target_include_directories(less_LESS_252_192_opt PRIVATE ${CMAKE_CURRENT_LIST_DIR}/less_LESS_252_192_opt)
    target_include_directories(less_LESS_252_192_opt PRIVATE ${PROJECT_SOURCE_DIR}/src/common/pqclean_shims)
    set(_LESS_OBJS ${_LESS_OBJS} $<TARGET_OBJECTS:less_LESS_252_192_opt>)
endif()

if(OQS_ENABLE_SIG_less_LESS_252_68)
    add_library(less_LESS_252_68_opt OBJECT sig_less_LESS_252_68.c less_LESS_252_68_opt/oqs_less.c less_LESS_252_68_opt/LESS.c less_LESS_252_68_opt/canonical.c less_LESS_252_68_opt/codes.c less_LESS_252_68_opt/fips202.c less_LESS_252_68_opt/keccakf1600.c less_LESS_252_68_opt/monomial.c less_LESS_252_68_opt/rng.c less_LESS_252_68_opt/seedtree.c less_LESS_252_68_opt/sort.c less_LESS_252_68_opt/transpose.c less_LESS_252_68_opt/utils.c)
    target_include_directories(less_LESS_252_68_opt PRIVATE ${CMAKE_CURRENT_LIST_DIR}/less_LESS_252_68_opt)
    target_include_directories(less_LESS_252_68_opt PRIVATE ${PROJECT_SOURCE_DIR}/src/common/pqclean_shims)
    set(_LESS_OBJS ${_LESS_OBJS} $<TARGET_OBJECTS:less_LESS_252_68_opt>)
endif()

if(OQS_ENABLE_SIG_less_LESS_252_45)
    add_library(less_LESS_252_45_opt OBJECT sig_less_LESS_252_45.c less_LESS_252_45_opt/oqs_less.c less_LESS_252_45_opt/LESS.c less_LESS_252_45_opt/canonical.c less_LESS_252_45_opt/codes.c less_LESS_252_45_opt/fips202.c less_LESS_252_45_opt/keccakf1600.c less_LESS_252_45_opt/monomial.c less_LESS_252_45_opt/rng.c less_LESS_252_45_opt/seedtree.c less_LESS_252_45_opt/sort.c less_LESS_252_45_opt/transpose.c less_LESS_252_45_opt/utils.c)
    target_include_directories(less_LESS_252_45_opt PRIVATE ${CMAKE_CURRENT_LIST_DIR}/less_LESS_252_45_opt)
    target_include_directories(less_LESS_252_45_opt PRIVATE ${PROJECT_SOURCE_DIR}/src/common/pqclean_shims)
    set(_LESS_OBJS ${_LESS_OBJS} $<TARGET_OBJECTS:less_LESS_252_45_opt>)
endif()

if(OQS_ENABLE_SIG_less_LESS_400_220)
    add_library(less_LESS_400_220_opt OBJECT sig_less_LESS_400_220.c less_LESS_400_220_opt/oqs_less.c less_LESS_400_220_opt/LESS.c less_LESS_400_220_opt/canonical.c less_LESS_400_220_opt/codes.c less_LESS_400_220_opt/fips202.c less_LESS_400_220_opt/keccakf1600.c less_LESS_400_220_opt/monomial.c less_LESS_400_220_opt/rng.c less_LESS_400_220_opt/seedtree.c less_LESS_400_220_opt/sort.c less_LESS_400_220_opt/transpose.c less_LESS_400_220_opt/utils.c)
    target_include_directories(less_LESS_400_220_opt PRIVATE ${CMAKE_CURRENT_LIST_DIR}/less_LESS_400_220_opt)
    target_include_directories(less_LESS_400_220_opt PRIVATE ${PROJECT_SOURCE_DIR}/src/common/pqclean_shims)
    set(_LESS_OBJS ${_LESS_OBJS} $<TARGET_OBJECTS:less_LESS_400_220_opt>)
endif()

if(OQS_ENABLE_SIG_less_LESS_400_102)
    add_library(less_LESS_400_102_opt OBJECT sig_less_LESS_400_102.c less_LESS_400_102_opt/oqs_less.c less_LESS_400_102_opt/LESS.c less_LESS_400_102_opt/canonical.c less_LESS_400_102_opt/codes.c less_LESS_400_102_opt/fips202.c less_LESS_400_102_opt/keccakf1600.c less_LESS_400_102_opt/monomial.c less_LESS_400_102_opt/rng.c less_LESS_400_102_opt/seedtree.c less_LESS_400_102_opt/sort.c less_LESS_400_102_opt/transpose.c less_LESS_400_102_opt/utils.c)
    target_include_directories(less_LESS_400_102_opt PRIVATE ${CMAKE_CURRENT_LIST_DIR}/less_LESS_400_102_opt)
    target_include_directories(less_LESS_400_102_opt PRIVATE ${PROJECT_SOURCE_DIR}/src/common/pqclean_shims)
    set(_LESS_OBJS ${_LESS_OBJS} $<TARGET_OBJECTS:less_LESS_400_102_opt>)
endif()

if(OQS_ENABLE_SIG_less_LESS_548_345)
    add_library(less_LESS_548_345_opt OBJECT sig_less_LESS_548_345.c less_LESS_548_345_opt/oqs_less.c less_LESS_548_345_opt/LESS.c less_LESS_548_345_opt/canonical.c less_LESS_548_345_opt/codes.c less_LESS_548_345_opt/fips202.c less_LESS_548_345_opt/keccakf1600.c less_LESS_548_345_opt/monomial.c less_LESS_548_345_opt/rng.c less_LESS_548_345_opt/seedtree.c less_LESS_548_345_opt/sort.c less_LESS_548_345_opt/transpose.c less_LESS_548_345_opt/utils.c)
    target_include_directories(less_LESS_548_345_opt PRIVATE ${CMAKE_CURRENT_LIST_DIR}/less_LESS_548_345_opt)
    target_include_directories(less_LESS_548_345_opt PRIVATE ${PROJECT_SOURCE_DIR}/src/common/pqclean_shims)
    set(_LESS_OBJS ${_LESS_OBJS} $<TARGET_OBJECTS:less_LESS_548_345_opt>)
endif()

if(OQS_ENABLE_SIG_less_LESS_548_137)
    add_library(less_LESS_548_137_opt OBJECT sig_less_LESS_548_137.c less_LESS_548_137_opt/oqs_less.c less_LESS_548_137_opt/LESS.c less_LESS_548_137_opt/canonical.c less_LESS_548_137_opt/codes.c less_LESS_548_137_opt/fips202.c less_LESS_548_137_opt/keccakf1600.c less_LESS_548_137_opt/monomial.c less_LESS_548_137_opt/rng.c less_LESS_548_137_opt/seedtree.c less_LESS_548_137_opt/sort.c less_LESS_548_137_opt/transpose.c less_LESS_548_137_opt/utils.c)
    target_include_directories(less_LESS_548_137_opt PRIVATE ${CMAKE_CURRENT_LIST_DIR}/less_LESS_548_137_opt)
    target_include_directories(less_LESS_548_137_opt PRIVATE ${PROJECT_SOURCE_DIR}/src/common/pqclean_shims)
    set(_LESS_OBJS ${_LESS_OBJS} $<TARGET_OBJECTS:less_LESS_548_137_opt>)
endif()

set(LESS_OBJS ${_LESS_OBJS} PARENT_SCOPE)