// SPDX-License-Identifier: MIT
#pragma once

// Namespace all externally visible MIRATH-TCITH-3A-SHORT symbols to avoid clashes with
// other OQS algorithms (including additional MIRATH parameter sets).
//
// This header is force-included via the build system for every source file that
// belongs to the MIRATH-TCITH-3A-SHORT reference implementation and its glue layer. It ensures
// that both declarations and definitions are rewritten to the corresponding
// OQS-prefixed symbols, eliminating duplicate symbol definitions when multiple
// variants are linked together.

#define AES256_CTR_DRBG_struct OQS_MIRATH_TCITH_3A_SHORT_AES256_CTR_DRBG_struct
#define AES256_CTR_DRBG_Update OQS_MIRATH_TCITH_3A_SHORT_AES256_CTR_DRBG_Update
#define AES256_ECB OQS_MIRATH_TCITH_3A_SHORT_AES256_ECB
#define AES_XOF_struct OQS_MIRATH_TCITH_3A_SHORT_AES_XOF_struct
#define crypto_sign OQS_MIRATH_TCITH_3A_SHORT_crypto_sign
#define crypto_sign_keypair OQS_MIRATH_TCITH_3A_SHORT_crypto_sign_keypair
#define crypto_sign_open OQS_MIRATH_TCITH_3A_SHORT_crypto_sign_open
#define DRBG_ctx OQS_MIRATH_TCITH_3A_SHORT_DRBG_ctx
#define handleErrors OQS_MIRATH_TCITH_3A_SHORT_handleErrors
#define randombytes OQS_MIRATH_TCITH_3A_SHORT_randombytes
#define randombytes_init OQS_MIRATH_TCITH_3A_SHORT_randombytes_init

#define seedexpander_init OQS_MIRATH_TCITH_3A_SHORT_seedexpander_init
#define seedexpander OQS_MIRATH_TCITH_3A_SHORT_seedexpander
#define seedexpander_shake_init OQS_MIRATH_TCITH_3A_SHORT_seedexpander_shake_init
#define seedexpander_shake_get_bytes OQS_MIRATH_TCITH_3A_SHORT_seedexpander_shake_get_bytes

#define shake_init OQS_MIRATH_TCITH_3A_SHORT_shake_init
#define hash_init OQS_MIRATH_TCITH_3A_SHORT_hash_init
#define hash_update OQS_MIRATH_TCITH_3A_SHORT_hash_update
#define hash_finalize OQS_MIRATH_TCITH_3A_SHORT_hash_finalize
#define hash_shake OQS_MIRATH_TCITH_3A_SHORT_hash_shake
#define hash_squeeze OQS_MIRATH_TCITH_3A_SHORT_hash_squeeze

#define mirath_keygen OQS_MIRATH_TCITH_3A_SHORT_mirath_keygen
#define mirath_sign OQS_MIRATH_TCITH_3A_SHORT_mirath_sign
#define mirath_verify OQS_MIRATH_TCITH_3A_SHORT_mirath_verify

#define rijndael_expand_seed OQS_MIRATH_TCITH_3A_SHORT_rijndael_expand_seed
#define rijndael_expand_share OQS_MIRATH_TCITH_3A_SHORT_rijndael_expand_share
#define rijndael_commit OQS_MIRATH_TCITH_3A_SHORT_rijndael_commit

#define unparse_public_key OQS_MIRATH_TCITH_3A_SHORT_unparse_public_key
#define parse_public_key OQS_MIRATH_TCITH_3A_SHORT_parse_public_key
#define unparse_secret_key OQS_MIRATH_TCITH_3A_SHORT_unparse_secret_key
#define parse_secret_key OQS_MIRATH_TCITH_3A_SHORT_parse_secret_key
#define unparse_signature OQS_MIRATH_TCITH_3A_SHORT_unparse_signature
#define parse_signature OQS_MIRATH_TCITH_3A_SHORT_parse_signature

#define mirath_matrix_init_zero OQS_MIRATH_TCITH_3A_SHORT_mirath_matrix_init_zero
#define mirath_matrix_expand_seed_public_matrix OQS_MIRATH_TCITH_3A_SHORT_mirath_matrix_expand_seed_public_matrix
#define mirath_matrix_expand_seed_secret_matrix OQS_MIRATH_TCITH_3A_SHORT_mirath_matrix_expand_seed_secret_matrix
#define mirath_matrix_compute_y OQS_MIRATH_TCITH_3A_SHORT_mirath_matrix_compute_y
#define mirath_tciht_compute_public_key OQS_MIRATH_TCITH_3A_SHORT_mirath_tciht_compute_public_key
#define mirath_matrix_decompress_secret_key OQS_MIRATH_TCITH_3A_SHORT_mirath_matrix_decompress_secret_key
#define mirath_matrix_decompress_pk OQS_MIRATH_TCITH_3A_SHORT_mirath_matrix_decompress_pk
#define mirath_matrix_ff_copy OQS_MIRATH_TCITH_3A_SHORT_mirath_matrix_ff_copy
#define mirath_matrix_ff_neg OQS_MIRATH_TCITH_3A_SHORT_mirath_matrix_ff_neg
#define mirath_matrix_ff_add OQS_MIRATH_TCITH_3A_SHORT_mirath_matrix_ff_add
#define mirath_matrix_ff_add_multiple OQS_MIRATH_TCITH_3A_SHORT_mirath_matrix_ff_add_multiple
#define mirath_matrix_ff_sub OQS_MIRATH_TCITH_3A_SHORT_mirath_matrix_ff_sub
#define mirath_matrix_ff_sub_multiple OQS_MIRATH_TCITH_3A_SHORT_mirath_matrix_ff_sub_multiple
#define mirath_matrix_ff_product OQS_MIRATH_TCITH_3A_SHORT_mirath_matrix_ff_product
#define mirath_matrix_ff_horizontal_concat OQS_MIRATH_TCITH_3A_SHORT_mirath_matrix_ff_horizontal_concat
#define mirath_matrix_ff_horizontal_split OQS_MIRATH_TCITH_3A_SHORT_mirath_matrix_ff_horizontal_split
#define mirath_matrix_ff_init_random OQS_MIRATH_TCITH_3A_SHORT_mirath_matrix_ff_init_random

#define mirath_ggm_tree_expand OQS_MIRATH_TCITH_3A_SHORT_mirath_ggm_tree_expand
#define mirath_ggm_tree_get_sibling_path OQS_MIRATH_TCITH_3A_SHORT_mirath_ggm_tree_get_sibling_path
#define mirath_ggm_tree_partial_expand OQS_MIRATH_TCITH_3A_SHORT_mirath_ggm_tree_partial_expand
#define mirath_ggm_tree_get_leaves OQS_MIRATH_TCITH_3A_SHORT_mirath_ggm_tree_get_leaves
#define mirath_ggm_tree_print_sibling_path OQS_MIRATH_TCITH_3A_SHORT_mirath_ggm_tree_print_sibling_path

#define mirath_commit OQS_MIRATH_TCITH_3A_SHORT_mirath_commit
#define mirath_commit_4x OQS_MIRATH_TCITH_3A_SHORT_mirath_commit_4x
#define mirath_tcith_internal_steps_pk OQS_MIRATH_TCITH_3A_SHORT_mirath_tcith_internal_steps_pk
#define commit_witness_polynomials OQS_MIRATH_TCITH_3A_SHORT_commit_witness_polynomials
#define compute_share OQS_MIRATH_TCITH_3A_SHORT_compute_share
#define compute_polynomial_proof OQS_MIRATH_TCITH_3A_SHORT_compute_polynomial_proof
#define recompute_polynomial_proof OQS_MIRATH_TCITH_3A_SHORT_recompute_polynomial_proof
#define mirath_tcith_expand_view_challenge OQS_MIRATH_TCITH_3A_SHORT_mirath_tcith_expand_view_challenge

#define KeccakP1600_Initialize OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600_Initialize
#include <stdint.h>

void OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600times4_StaticInitialize(void);
void OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600times4_AddByte(void *states, unsigned int instanceIndex, unsigned char byte, unsigned int offset);

#define KeccakP1600_AddByte OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600_AddByte
#define KeccakP1600_AddBytes OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600_AddBytes
#define KeccakP1600_OverwriteBytes OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600_OverwriteBytes
#define KeccakP1600_OverwriteWithZeroes OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600_OverwriteWithZeroes
#define KeccakP1600_Permute_Nrounds OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600_Permute_Nrounds
#define KeccakP1600_Permute_12rounds OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600_Permute_12rounds
#define KeccakP1600_Permute_24rounds OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600_Permute_24rounds
#define KeccakP1600_ExtractBytes OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600_ExtractBytes
#define KeccakP1600_ExtractAndAddBytes OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600_ExtractAndAddBytes
#define KeccakP1600_AddBytesInLane OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600_AddBytesInLane
#define KeccakP1600_AddLanes OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600_AddLanes
#define KeccakP1600_OverwriteBytesInLane OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600_OverwriteBytesInLane
#define KeccakP1600_OverwriteLanes OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600_OverwriteLanes
#define KeccakP1600_ExtractBytesInLane OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600_ExtractBytesInLane
#define KeccakP1600_ExtractLanes OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600_ExtractLanes
#define KeccakP1600_ExtractAndAddBytesInLane OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600_ExtractAndAddBytesInLane
#define KeccakP1600_ExtractAndAddLanes OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600_ExtractAndAddLanes
#define Keccak_HashInitialize OQS_MIRATH_TCITH_3A_SHORT_Keccak_HashInitialize
#define Keccak_HashInitializetimes4 OQS_MIRATH_TCITH_3A_SHORT_Keccak_HashInitializetimes4
#define Keccak_HashUpdate OQS_MIRATH_TCITH_3A_SHORT_Keccak_HashUpdate
#define Keccak_HashUpdatetimes4 OQS_MIRATH_TCITH_3A_SHORT_Keccak_HashUpdatetimes4
#define Keccak_HashFinal OQS_MIRATH_TCITH_3A_SHORT_Keccak_HashFinal
#define Keccak_HashFinaltimes4 OQS_MIRATH_TCITH_3A_SHORT_Keccak_HashFinaltimes4
#define Keccak_HashSqueeze OQS_MIRATH_TCITH_3A_SHORT_Keccak_HashSqueeze
#define Keccak_HashSqueezetimes4 OQS_MIRATH_TCITH_3A_SHORT_Keccak_HashSqueezetimes4
#define KeccakSponge OQS_MIRATH_TCITH_3A_SHORT_KeccakSponge
#define KeccakSpongeInitialize OQS_MIRATH_TCITH_3A_SHORT_KeccakSpongeInitialize
#define KeccakSpongeAbsorb OQS_MIRATH_TCITH_3A_SHORT_KeccakSpongeAbsorb
#define KeccakSpongeAbsorbLastFewBits OQS_MIRATH_TCITH_3A_SHORT_KeccakSpongeAbsorbLastFewBits
#define KeccakSpongeSqueeze OQS_MIRATH_TCITH_3A_SHORT_KeccakSpongeSqueeze
#define KeccakWidth1600_Sponge OQS_MIRATH_TCITH_3A_SHORT_KeccakWidth1600_Sponge
#define KeccakWidth1600_SpongeAbsorb OQS_MIRATH_TCITH_3A_SHORT_KeccakWidth1600_SpongeAbsorb
#define KeccakWidth1600_SpongeAbsorbLastFewBits OQS_MIRATH_TCITH_3A_SHORT_KeccakWidth1600_SpongeAbsorbLastFewBits
#define KeccakWidth1600_SpongeInitialize OQS_MIRATH_TCITH_3A_SHORT_KeccakWidth1600_SpongeInitialize
#define KeccakWidth1600_SpongeSqueeze OQS_MIRATH_TCITH_3A_SHORT_KeccakWidth1600_SpongeSqueeze
#define KeccakWidth1600_12rounds_Sponge OQS_MIRATH_TCITH_3A_SHORT_KeccakWidth1600_12rounds_Sponge
#define KeccakWidth1600_12rounds_SpongeInitialize OQS_MIRATH_TCITH_3A_SHORT_KeccakWidth1600_12rounds_SpongeInitialize
#define KeccakWidth1600_12rounds_SpongeAbsorb OQS_MIRATH_TCITH_3A_SHORT_KeccakWidth1600_12rounds_SpongeAbsorb
#define KeccakWidth1600_12rounds_SpongeAbsorbLastFewBits OQS_MIRATH_TCITH_3A_SHORT_KeccakWidth1600_12rounds_SpongeAbsorbLastFewBits
#define KeccakWidth1600_12rounds_SpongeSqueeze OQS_MIRATH_TCITH_3A_SHORT_KeccakWidth1600_12rounds_SpongeSqueeze
#define KeccakWidth1600times4_SpongeAbsorb OQS_MIRATH_TCITH_3A_SHORT_KeccakWidth1600times4_SpongeAbsorb
#define KeccakWidth1600times4_SpongeAbsorbLastFewBits OQS_MIRATH_TCITH_3A_SHORT_KeccakWidth1600times4_SpongeAbsorbLastFewBits
#define KeccakWidth1600times4_SpongeInitialize OQS_MIRATH_TCITH_3A_SHORT_KeccakWidth1600times4_SpongeInitialize
#define KeccakWidth1600times4_SpongeSqueeze OQS_MIRATH_TCITH_3A_SHORT_KeccakWidth1600times4_SpongeSqueeze
#define KeccakP1600times4_AddByte OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600times4_AddByte
#define KeccakP1600times4_AddBytes OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600times4_AddBytes
#define KeccakP1600times4_AddLanesAll OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600times4_AddLanesAll
#define KeccakP1600times4_ExtractAndAddBytes OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600times4_ExtractAndAddBytes
#define KeccakP1600times4_ExtractAndAddLanesAll OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600times4_ExtractAndAddLanesAll
#define KeccakP1600times4_ExtractBytes OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600times4_ExtractBytes
#define KeccakP1600times4_ExtractLanesAll OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600times4_ExtractLanesAll
#define KeccakP1600times4_InitializeAll OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600times4_InitializeAll
#define KeccakP1600times4_OverwriteBytes OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600times4_OverwriteBytes
#define KeccakP1600times4_OverwriteLanesAll OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600times4_OverwriteLanesAll
#define KeccakP1600times4_OverwriteWithZeroes OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600times4_OverwriteWithZeroes
#define KeccakP1600times4_PermuteAll_12rounds OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600times4_PermuteAll_12rounds
#define KeccakP1600times4_PermuteAll_24rounds OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600times4_PermuteAll_24rounds
#define KeccakP1600times4_PermuteAll_4rounds OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600times4_PermuteAll_4rounds
#define KeccakP1600times4_PermuteAll_6rounds OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600times4_PermuteAll_6rounds
#define KeccakP1600times4_StaticInitialize OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600times4_StaticInitialize
#define KeccakF1600_FastLoop_Absorb OQS_MIRATH_TCITH_3A_SHORT_KeccakF1600_FastLoop_Absorb
#define KeccakP1600_12rounds_FastLoop_Absorb OQS_MIRATH_TCITH_3A_SHORT_KeccakP1600_12rounds_FastLoop_Absorb
#define KECCAK_IMPL_NAMESPACE OQS_MIRATH_TCITH_3A_SHORT_KECCAK_IMPL_NAMESPACE

#define SHAKE128 OQS_MIRATH_TCITH_3A_SHORT_SHAKE128
#define SHAKE256 OQS_MIRATH_TCITH_3A_SHORT_SHAKE256
#define SHA3_224 OQS_MIRATH_TCITH_3A_SHORT_SHA3_224
#define SHA3_256 OQS_MIRATH_TCITH_3A_SHORT_SHA3_256
#define SHA3_384 OQS_MIRATH_TCITH_3A_SHORT_SHA3_384
#define SHA3_512 OQS_MIRATH_TCITH_3A_SHORT_SHA3_512
