// SPDX-License-Identifier: MIT
#pragma once

// Namespace all externally visible FAEST 192-short symbols to avoid clashes with
// other OQS algorithms (including additional FAEST parameter sets).
//
// This header is force-included via the build system for every source file that
// belongs to the FAEST 192-short reference implementation and its glue layer.
// It ensures that both declarations and definitions are rewritten to the
// corresponding OQS-prefixed symbols, eliminating duplicate symbol definitions
// when multiple variants are linked together.

// needs to be cleaned and update according to new files

#define AES256_CTR_DRBG_Update OQS_FAEST_192S_AES256_CTR_DRBG_Update
#define AES256_ECB OQS_FAEST_192S_AES256_ECB
#define cmp_const OQS_FAEST_192S_cmp_const
#define crypto_sign OQS_FAEST_192S_crypto_sign
#define crypto_sign_keypair OQS_FAEST_192S_crypto_sign_keypair
#define crypto_sign_open OQS_FAEST_192S_crypto_sign_open
#define DRBG_ctx OQS_FAEST_192S_DRBG_ctx
#define handleErrors OQS_FAEST_192S_handleErrors
#define int32_sort OQS_FAEST_192S_int32_sort
#define Keccak_HashFinal OQS_FAEST_192S_Keccak_HashFinal
#define Keccak_HashFinaltimes4 OQS_FAEST_192S_Keccak_HashFinaltimes4
#define Keccak_HashInitialize OQS_FAEST_192S_Keccak_HashInitialize
#define Keccak_HashInitializetimes4 OQS_FAEST_192S_Keccak_HashInitializetimes4
#define Keccak_HashSqueeze OQS_FAEST_192S_Keccak_HashSqueeze
#define Keccak_HashSqueezetimes4 OQS_FAEST_192S_Keccak_HashSqueezetimes4
#define Keccak_HashUpdate OQS_FAEST_192S_Keccak_HashUpdate
#define Keccak_HashUpdatetimes4 OQS_FAEST_192S_Keccak_HashUpdatetimes4

#define KeccakP1600_Initialize OQS_FAEST_192S_KeccakP1600_Initialize
#include <stdint.h>

static inline void OQS_FAEST_192S_KeccakP1600_AddByte(void *state, unsigned char byte, unsigned int offset) {
	((unsigned char *) state)[offset] ^= byte;
}

#define KeccakP1600_AddByte OQS_FAEST_192S_KeccakP1600_AddByte
#define KeccakP1600_AddBytes OQS_FAEST_192S_KeccakP1600_AddBytes
#define KeccakP1600_AddBytesInLane OQS_FAEST_192S_KeccakP1600_AddBytesInLane
#define KeccakP1600_AddLanes OQS_FAEST_192S_KeccakP1600_AddLanes
#define KeccakP1600_ExtractAndAddBytes OQS_FAEST_192S_KeccakP1600_ExtractAndAddBytes
#define KeccakP1600_ExtractAndAddBytesInLane OQS_FAEST_192S_KeccakP1600_ExtractAndAddBytesInLane
#define KeccakP1600_ExtractAndAddLanes OQS_FAEST_192S_KeccakP1600_ExtractAndAddLanes
#define KeccakP1600_ExtractBytes OQS_FAEST_192S_KeccakP1600_ExtractBytes
#define KeccakP1600_ExtractBytesInLane OQS_FAEST_192S_KeccakP1600_ExtractBytesInLane
#define KeccakP1600_ExtractLanes OQS_FAEST_192S_KeccakP1600_ExtractLanes
#define KeccakP1600_OverwriteBytes OQS_FAEST_192S_KeccakP1600_OverwriteBytes
#define KeccakP1600_OverwriteBytesInLane OQS_FAEST_192S_KeccakP1600_OverwriteBytesInLane
#define KeccakP1600_OverwriteLanes OQS_FAEST_192S_KeccakP1600_OverwriteLanes
#define KeccakP1600_OverwriteWithZeroes OQS_FAEST_192S_KeccakP1600_OverwriteWithZeroes
#define KeccakP1600_Permute_12rounds OQS_FAEST_192S_KeccakP1600_Permute_12rounds
#define KeccakP1600_Permute_24rounds OQS_FAEST_192S_KeccakP1600_Permute_24rounds
#define KeccakP1600_Permute_Nrounds OQS_FAEST_192S_KeccakP1600_Permute_Nrounds

#define KeccakF1600_FastLoop_Absorb OQS_FAEST_192S_KeccakF1600_FastLoop_Absorb
#define KeccakP1600_12rounds_FastLoop_Absorb OQS_FAEST_192S_KeccakP1600_12rounds_FastLoop_Absorb
#define KeccakP1600times4_AddByte OQS_FAEST_192S_KeccakP1600times4_AddByte
#define KeccakP1600times4_AddBytes OQS_FAEST_192S_KeccakP1600times4_AddBytes
#define KeccakP1600times4_AddLanesAll OQS_FAEST_192S_KeccakP1600times4_AddLanesAll
#define KeccakP1600times4_ExtractAndAddBytes OQS_FAEST_192S_KeccakP1600times4_ExtractAndAddBytes
#define KeccakP1600times4_ExtractAndAddLanesAll OQS_FAEST_192S_KeccakP1600times4_ExtractAndAddLanesAll
#define KeccakP1600times4_ExtractBytes OQS_FAEST_192S_KeccakP1600times4_ExtractBytes
#define KeccakP1600times4_ExtractLanesAll OQS_FAEST_192S_KeccakP1600times4_ExtractLanesAll
#define KeccakP1600times4_InitializeAll OQS_FAEST_192S_KeccakP1600times4_InitializeAll
#define KeccakP1600times4_OverwriteBytes OQS_FAEST_192S_KeccakP1600times4_OverwriteBytes
#define KeccakP1600times4_OverwriteLanesAll OQS_FAEST_192S_KeccakP1600times4_OverwriteLanesAll
#define KeccakP1600times4_OverwriteWithZeroes OQS_FAEST_192S_KeccakP1600times4_OverwriteWithZeroes
#define KeccakP1600times4_PermuteAll_12rounds OQS_FAEST_192S_KeccakP1600times4_PermuteAll_12rounds
#define KeccakP1600times4_PermuteAll_24rounds OQS_FAEST_192S_KeccakP1600times4_PermuteAll_24rounds
#define KeccakP1600times4_PermuteAll_4rounds OQS_FAEST_192S_KeccakP1600times4_PermuteAll_4rounds
#define KeccakP1600times4_PermuteAll_6rounds OQS_FAEST_192S_KeccakP1600times4_PermuteAll_6rounds
#define KeccakP1600times4_StaticInitialize OQS_FAEST_192S_KeccakP1600times4_StaticInitialize
#define KeccakWidth1600_Sponge OQS_FAEST_192S_KeccakWidth1600_Sponge
#define KeccakWidth1600_SpongeAbsorb OQS_FAEST_192S_KeccakWidth1600_SpongeAbsorb
#define KeccakWidth1600_SpongeAbsorbLastFewBits OQS_FAEST_192S_KeccakWidth1600_SpongeAbsorbLastFewBits
#define KeccakWidth1600_SpongeInitialize OQS_FAEST_192S_KeccakWidth1600_SpongeInitialize
#define KeccakWidth1600_SpongeSqueeze OQS_FAEST_192S_KeccakWidth1600_SpongeSqueeze
#define KeccakWidth1600times4_SpongeAbsorb OQS_FAEST_192S_KeccakWidth1600times4_SpongeAbsorb
#define KeccakWidth1600times4_SpongeAbsorbLastFewBits OQS_FAEST_192S_KeccakWidth1600times4_SpongeAbsorbLastFewBits
#define KeccakWidth1600times4_SpongeInitialize OQS_FAEST_192S_KeccakWidth1600times4_SpongeInitialize
#define KeccakWidth1600times4_SpongeSqueeze OQS_FAEST_192S_KeccakWidth1600times4_SpongeSqueeze
#define memset_volatile OQS_FAEST_192S_memset_volatile
#define randombytes OQS_FAEST_192S_randombytes
#define randombytes_init OQS_FAEST_192S_randombytes_init
#define seedexpander OQS_FAEST_192S_seedexpander
#define seedexpander_init OQS_FAEST_192S_seedexpander_init
#define sig_perk_challenges_from_bytes OQS_FAEST_192S_sig_perk_challenges_from_bytes
#define sig_perk_expand_theta_partial_tree OQS_FAEST_192S_sig_perk_expand_theta_partial_tree
#define sig_perk_expand_theta_tree OQS_FAEST_192S_sig_perk_expand_theta_tree
#define sig_perk_gen_commitment_cmt_1_i OQS_FAEST_192S_sig_perk_gen_commitment_cmt_1_i
#define sig_perk_generate_keypair OQS_FAEST_192S_sig_perk_generate_keypair
#define sig_perk_gen_first_challenge OQS_FAEST_192S_sig_perk_gen_first_challenge
#define sig_perk_gen_instance_commitment_cmt_1 OQS_FAEST_192S_sig_perk_gen_instance_commitment_cmt_1
#define sig_perk_gen_instance_commitments OQS_FAEST_192S_sig_perk_gen_instance_commitments
#define sig_perk_gen_pi_i_and_v_i OQS_FAEST_192S_sig_perk_gen_pi_i_and_v_i
#define sig_perk_gen_second_challenge OQS_FAEST_192S_sig_perk_gen_second_challenge
#define sig_perk_gen_vect_v OQS_FAEST_192S_sig_perk_gen_vect_v
#define sig_perk_get_theta_partial_tree_seeds OQS_FAEST_192S_sig_perk_get_theta_partial_tree_seeds
#define sig_perk_hash_final OQS_FAEST_192S_sig_perk_hash_final
#define sig_perk_hash_init OQS_FAEST_192S_sig_perk_hash_init
#define sig_perk_hash_update OQS_FAEST_192S_sig_perk_hash_update
#define sig_perk_mat_set_random OQS_FAEST_192S_sig_perk_mat_set_random
#define sig_perk_mat_vect_mul OQS_FAEST_192S_sig_perk_mat_vect_mul
#define sig_perk_perm_compose OQS_FAEST_192S_sig_perk_perm_compose
#define sig_perk_perm_compose_inv OQS_FAEST_192S_sig_perk_perm_compose_inv
#define sig_perk_perm_decode OQS_FAEST_192S_sig_perk_perm_decode
#define sig_perk_perm_encode OQS_FAEST_192S_sig_perk_perm_encode
#define sig_perk_perm_gen_given_random_input OQS_FAEST_192S_sig_perk_perm_gen_given_random_input
#define sig_perk_perm_gen_pi_1 OQS_FAEST_192S_sig_perk_perm_gen_pi_1
#define sig_perk_perm_inverse OQS_FAEST_192S_sig_perk_perm_inverse
#define sig_perk_perm_set_random OQS_FAEST_192S_sig_perk_perm_set_random
#define sig_perk_perm_vect_permute OQS_FAEST_192S_sig_perk_perm_vect_permute
#define sig_perk_prg OQS_FAEST_192S_sig_perk_prg
#define sig_perk_prg_init OQS_FAEST_192S_sig_perk_prg_init
#define sig_perk_private_key_from_bytes OQS_FAEST_192S_sig_perk_private_key_from_bytes
#define sig_perk_private_key_to_bytes OQS_FAEST_192S_sig_perk_private_key_to_bytes
#define sig_perk_public_key_from_bytes OQS_FAEST_192S_sig_perk_public_key_from_bytes
#define sig_perk_public_key_to_bytes OQS_FAEST_192S_sig_perk_public_key_to_bytes
#define sig_perk_sign OQS_FAEST_192S_sig_perk_sign
#define sig_perk_signature_from_bytes OQS_FAEST_192S_sig_perk_signature_from_bytes
#define sig_perk_signature_to_bytes OQS_FAEST_192S_sig_perk_signature_to_bytes
#define sig_perk_vect1_add OQS_FAEST_192S_sig_perk_vect1_add
#define sig_perk_vect1_compute_rank OQS_FAEST_192S_sig_perk_vect1_compute_rank
#define sig_perk_vect1_mult_scalar_vect OQS_FAEST_192S_sig_perk_vect1_mult_scalar_vect
#define sig_perk_vect1_set_random_list OQS_FAEST_192S_sig_perk_vect1_set_random_list
#define sig_perk_vect2_add OQS_FAEST_192S_sig_perk_vect2_add
#define sig_perk_vect2_mult_scalar_vect OQS_FAEST_192S_sig_perk_vect2_mult_scalar_vect
#define sig_perk_vect2_sub OQS_FAEST_192S_sig_perk_vect2_sub
#define sig_perk_verbose_print_challenges OQS_FAEST_192S_sig_perk_verbose_print_challenges
#define sig_perk_verbose_print_matrix OQS_FAEST_192S_sig_perk_verbose_print_matrix
#define sig_perk_verbose_print_signature OQS_FAEST_192S_sig_perk_verbose_print_signature
#define sig_perk_verbose_print_signature_raw OQS_FAEST_192S_sig_perk_verbose_print_signature_raw
#define sig_perk_verbose_print_string OQS_FAEST_192S_sig_perk_verbose_print_string
#define sig_perk_verbose_print_theta_cmt_1_and_v OQS_FAEST_192S_sig_perk_verbose_print_theta_cmt_1_and_v
#define sig_perk_verbose_print_thetas OQS_FAEST_192S_sig_perk_verbose_print_thetas
#define sig_perk_verbose_print_uint16_t_array OQS_FAEST_192S_sig_perk_verbose_print_uint16_t_array
#define sig_perk_verbose_print_uint8_t_array OQS_FAEST_192S_sig_perk_verbose_print_uint8_t_array
#define sig_perk_verbose_print_x OQS_FAEST_192S_sig_perk_verbose_print_x
#define sig_perk_verbose_print_y OQS_FAEST_192S_sig_perk_verbose_print_y
#define sig_perk_verify OQS_FAEST_192S_sig_perk_verify
#define uint32_sort OQS_FAEST_192S_uint32_sort
