name: Push tests

permissions:
  contents: read

on:
  push:
    branches-ignore: 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  ext:
    runs-on: ubuntu-latest
    container:
      image: openquantumsafe/ci-ubuntu-latest:latest
    steps:
      - run: lscpu
